# Please insert new items alphabetically.

infra:
  members:
    - alexandre-zia-movile
    - alexei-znamensky-movile
    - demetrios-andrigo-movile
    - fabio-santos-movile
    - hugo-cisneiros-movile
    - hugo-cisneiros-movile
    - jean-feltrin-movile
    - bruno-rossi-movile 
    - maycson-fonseca-movile
    - tiago-cruz-movile

  channel:
    "#infra"

  exclude_titles:
    - WIP

  quotes:
    - ...

releases-smartphones-android:
  members:
    - rene-argento-movile
    - jefferson-silva-movile
    - bernardo-amaral-movile
    - tiago-chaves-movile

  channel:
    "#it-br-android-dev"

  exclude_titles:
    - WIP

  quotes:
    - ...

releases-smartphones-ios:
  members:
    - bruno-rocha-movile
    - rafael-alencar-movile
    - mateus-silveira-movile

  channel:
    "#it-br-ios-dev"

  exclude_titles:
    - WIP

  quotes:
    - ...

releases-smartphones-multiplat:
  members:
    - gustavo-silva-movile
    - ricardo-charf-movile

  channel:
    "#it-br-multiplat-dev"

  exclude_titles:
    - WIP

  quotes:
    - ...