# Please insert new items alphabetically.

releases-smartphones-android:
  members:
    - rene-argento-movile
    - jefferson-silva-movile
    - bernardo-amaral-movile
    - tiago-chaves-movile
    - renan-lukas-movile

  channel:
    "#it-br-android-dev"

  exclude_titles:
    - WIP

  quotes:
    - ...

releases-smartphones-ios:
  members:
    - rafael-alencar-movile
    - mateus-silveira-movile
    - felipe-valio-movile
    - matheus-maaz-movile

  channel:
    "#it-br-ios-dev"

  exclude_titles:
    - WIP

  quotes:
    - ...

releases-smartphones-multiplat:
  members:
    - gustavo-silva-movile
    - ricardo-charf-movile

  channel:
    "#it-br-multiplat"

  exclude_titles:
    - WIP

  quotes:
    - ...

rapiddo-ios:
  members:
    - bruno-rocha-movile
    - mateus-silveira-movile

  channel:
    "#ios-dev"

  exclude_titles:
    - WIP

  quotes:
    - ...