# Please insert new items alphabetically.

core-formats:
  members:
    - bruno-rocha-movile
    - rafael-alencar-movile
    - mateus-silveira-movile

  channel:
    "#it-br-ios-dev"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP
    - "[DO NOT SEAL]"
    - "[DON'T SEAL]"
    - DO NOT SEAL
    - DON'T SEAL

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - We focus on users - always starting with ‘why’ we are doing something, not ‘what’ we are doing.
    - If it’s gonna take more than 30 minutes, or it needs deploying - write a card for it and chat to Shilpa.
    - Try to pair when possible.
    - Pick up work from the 'ready column' - don't cherry pick from the backlog/ice box or ‘next’ column.
    - Any excuse for cake - or generally celebrating awesomeness
    - Never be afraid to suggest better ways of working.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge
    - Ask if anyone needs support before picking up new work
    - Be considerate to remote workers
    - Avoid gendered language when it isn’t needed
    - Turn up to meetings on time, one person speaks at a time
    - Stories should start with a user need
    - It’s not done until it’s in the hands of the people who need it
    - When working at home, dial in to stand-up
    - Keep things up-to-date - like the digital wall, team calendar
    - Communicate what you’re working on - make sure you don’t leave people out of the loop
    - Trello should reflect what everyone’s working on - if it's going to take longer than 30 minutes or it's going to need to be deployed - write a card and chat with Jen.
    - Meetings must have a clear purpose and make the best use of everyone’s time
    - Keep our desks and work spaces tidy (including the tea stand)
    - Get involved with user research - everyone should spend 2 hours every 6 weeks learning about our users
